services:
    nextcloud:
        build:
            dockerfile: ./Dockerfile
        container_name: nextcloud
        volumes:
            - /srv/http/nextcloud/master/apps-repos/tables:/var/www/server/apps/tables
        networks:
            - testnet

networks:
    testnet:
